src/data/gitmojis.json

Adds ➕ as emoji for 'Added dependecy' and ➖ for 'Removed dependency'
Just wondering, should I change to 'Added dependencies' & 'Removed dependencies' (plural) ?

✨ added ➕ & ➖

---

src/data/gitmojis.json

Ref. #15 
- 🚨 Format gitmojis.json file to follow RFC 4627
- ✨ Adding 🐳 emoji for Docker concerned things
- ⚡️ Add yarn.lock file to speed up dependencies installation with Yarn

✨ Adding 🐳 emoji for Docker concerned things

---

.github/CONTRIBUTING.md

There were a few small typos:
- 1 double word, line 5
- 1 wrong reference, line 20

📝 Fixed typos

---

src/data/gitmojis.json
src/styles/_includes/_vars.scss
src/styles/style.scss

✨ Added 📈 for analytics and tracking commits

---

src/data/gitmojis.json

✨Added typo emoji (✏️)

---

src/data/gitmojis.json

Add hankey emoji on gitmoji
Emoji for code that you know is a crap and you need to improve in the future
#40

Add hankey emoji

---

src/data/gitmojis.json

I noticed not all descriptions had a period. It's now the case.

Adding a period to every description

---

README.md

Fixed typo in read me
Signed-off-by: jmona789 <jmona789@gmail.com>

:memo: Fixed typo in read me

---

src/data/gitmojis.json

For compiled files or packages, from issue #61
- [ x ] All tests passed.
Signed-off-by: viktorstrate <viktorstrate@gmail.com>

:sparkles: Added :package: for compiled files, closes #61

---

package.json
yarn.lock

This fixes an issue when you need to install jsonlint manually after cloning the repo in order to run test.
This fixes issue #74.

🔧 Add jsonlint as dependency

---

src/data/gitmojis.json
src/styles/_includes/_vars.scss
src/styles/style.scss

For issue https://github.com/carloscuesta/gitmoji/issues/68

✨ 💄 Added 🚚  json and style updates

---

src/data/gitmojis.json

Add 📄 icon for adding/updating license.
Resolves #79.

✨ Add 📄 icon for adding/updating license

---

src/data/gitmojis.json

add :bento: for assets management

✨ add 🍱  for assets management

---

src/data/gitmojis.json

Fixed the spelling of 'accessibility' to be correct.
Did not run tests, as this is for spelling only.

Fix spelling of emoji description ✏️

---

src/data/contributors.json
src/data/gitmojis.json
src/styles/_includes/_vars.scss

Update the refactor gitmoji from `:hammer:` to `:recycle:`
Fixes #143

✨ Update 🔨 to ♻️

---

package.json
yarn.lock

⬆️ Update dependencies

---

src/data/gitmojis.json
src/styles/_includes/_vars.scss

✨ feature #176 for mocking things

✨ Add 🤡 for mocking things

---

src/data/gitmojis.json

Emoji for easter egg

---

src/data/gitmojis.json
src/styles/_includes/_vars.scss

 ✨ add 🙈 for gitignore

---

src/data/contributors.json
src/data/gitmojis.json

✨ Add 📸 for snapshots

---

src/data/gitmojis.json

I've fixed the formatting of the SEO Gitmoji in gitmojis.json

:art: Fix formatting in gitmojis.json

---

src/data/gitmojis.json

@carloscuesta I just noticed I had a typo. Sorry!

✏️ Fixes typo in TypeScript 🙈 

---

src/data/gitmojis.json

closes #267 
Changes description of ✅ emoji from `Adding tests.` → `Updating tests.`.

💬 change text of test emoji

---

.github/CONTRIBUTING.md

Just adding the entity's explanation in contributing guideline.

📝 Adding entity's explanation in contributing guideline.

---

src/data/gitmojis.json

I've made the two changes discussed in #308. Only `gitmojis.json` changed.

bitbucket compatibility fix

---

src/data/gitmojis.json

Add :seedling: icon for adding/updating seed files
Resolves #144.

✨ Add 🌱 icon for adding/updating seed files

---

src/styles/_includes/_vars.scss

Add missing seedling color. 
Related to #353.

💄 Add seedling color

---

src/styles/_includes/_vars.scss

Looks like the name was updated in https://github.com/carloscuesta/gitmoji/pull/313. 
This PR fixes the `poop` background color.

🐛 Fix poop color

---

src/data/schema.json

Add entity field to JSON Schema

---

.github/FUNDING.yml

Add github sponsors as a funding method

💖 Add github to funding file

---

package.json
src/components/GitmojiList/index.js
src/pages/_document.js
yarn.lock

Fixes https://github.com/carloscuesta/gitmoji/issues/370

✨ Bring back copy to clipboard

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json
src/styles/_includes/_vars.scss

Add the :goal_net: emoji in order to fix issue #292

✨ Add 🥅 emoji

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json
src/styles/_includes/_vars.scss

Was looking for an emoji for deprecating code, came across #178.
Found the waste basket a good proposal. So here it is!

🗑 for deprecating code 

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

Closes https://github.com/carloscuesta/gitmoji/issues/395.
Adds "or updating" to the description of some emojis.

:speech_balloon: Add "or updating" to some emojis

---

src/styles/_includes/_vars.scss

🐛 Add pencil2's color

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

💬 Specify some descriptions using 'Adding' word

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

Related to #397.
Preference go to updating the already existing :bulb: emoji description to "Adding or updating comments in code" as it is the most upvoted comment.

Updating :bulb: emoji description

---

README.md

It's written in the README that you can implement the Gitmoji badge on your `GitHub project` wich is platform agnostic. I propose to remove the GitHub specification.

📝 Removing GitHub project specification

---

src/data/gitmojis.json

Implementation of #343 due to inactivity of the author.
----
```html
<p>Entity: &#x1F4C8;</p>
```
<p>Entity: &#x1F4C8;</p>
----
Closed #343

🐛 Add chart_with_upwards_trend's entity

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

See #348 and #462 
Closes #348
Closes #462

🔥 Remove :ok_hand: gitmoji

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

Current 🔧 's description is `Changing configuration files.`. Since there is like a convention for gitmoji's description (the use of `Adding or updating...`) I propose to update it to `Adding or updating configuration files.`

💬 Update 🔧 description

---

README.md

:memo: Add lalalilo/gitmemoji to related projects

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json
src/styles/_includes/_vars.scss

Add 🔨 gitmoji

---

README.md

Hello all 👋
@johannchopin and I have made an browser extension to efficiently search and copy gitmojis (code and emoji).  
The extension is available for [Chrome](https://chrome.google.com/webstore/detail/gitmoji-browser-extension/lkjogeoldakjceempbkdahkojohmbaja) and for [Firefox](https://addons.mozilla.org/fr/firefox/addon/gitmoji-browser-extension/)
If you want to give some feedback, help or want to see who it is used, here is the [ link to the github repository](https://github.com/johannchopin/gitmoji-browser-extension).
:wave: remarks welcome :unicorn:

📝 Add the gitmoji browser extension in the list "related tools"

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

Fix spelling

---

package.json

🔖 Bump version to 2.1.0

---

README.md

https://marketplace.visualstudio.com/items?itemName=Vtrois.gitmoji-vscode
https://github.com/vtrois/gitmoji-vscode

📝 Add gitmoji-vscode-extension in related tools

---

.github/CONTRIBUTING.md
src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

Fixes https://github.com/carloscuesta/gitmoji/issues/554

✏️  Use present form on verbs

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

This pull request resolves #564.

✏️ Make hammer gitmoji more general

---

README.md

I've added my macOS App to the readme.

:memo: - Add related tool for macOS

---

README.md

 📝 Add related tool for SublimeText

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json
src/styles/_includes/_vars.scss

Add :passport_control: to signify work related to authorization

Add passport_control emoji

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json
src/styles/_includes/_vars.scss

Add gitmoji for :adhesive_bandage: simple fix for non-critical issue.
* Code: :adhesive_bandage:
* Proposed name: :simple_fix: 
Appropriate for commits where we want to emphasize that it is a small change that fixes something, without worrying about the origin: maybe it's a bug, maybe a forgotten requirement, maybe a response to an external change 🤷
Closes https://github.com/carloscuesta/gitmoji/issues/605.
Updated snapshot with `npm test -- -u`
Thanks! 🙏

Add emoji simple fix

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/CarbonAd/__tests__/__snapshots__/carbonAd.spec.js.snap
src/components/CarbonAd/__tests__/carbonAd.spec.js
src/components/CarbonAd/index.js
src/pages/about.js
src/pages/contributors.js
src/pages/index.js
src/utils/theme/theme.css

This PR introduces [CarbonAds](https://www.carbonads.net/). I'm trying to make Open Source sustainable, can't really depend on donations or sponsors since they're difficult to get.

❤️ Introduce CarbonAds 

---

.github/workflows/lock.yml

This action will automatically lock issues and pull requests that are closed and inactive.

🔧  Introduce github/lock action flow

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/Gitmoji/index.js
src/components/GitmojiList/Toolbar/index.js
src/components/GitmojiList/Toolbar/styles.module.css
src/components/GitmojiList/__tests__/__snapshots__/gitmojiList.spec.js.snap
src/components/GitmojiList/__tests__/gitmojiList.spec.js
src/components/GitmojiList/index.js

This revamps and close #411. Thanks @dorlugasigal

✨ Add Search to GitmojiList

---

README.md
src/__tests__/__snapshots__/pages.spec.js.snap
src/__tests__/pages.spec.js
src/components/Layout/Hamburger/index.js
src/pages/related-tools.js

As we agreed in #496, we're moving the list of related tools to the website 🎉 
This fixes #496

✨ Add "related-tools" page 

---

README.md
package.json
src/__tests__/__snapshots__/pages.spec.js.snap
src/components/Layout/Header/index.js
src/components/Layout/__tests__/__snapshots__/layout.spec.js.snap
src/components/SEO/index.js
src/pages/about.js

♻️ Update website domain to gitmoji.dev

---

src/components/GitmojiList/Toolbar/styles.module.css

💄 Adjust search input dark mode styles

---

src/components/GitmojiList/Toolbar/ListModeSelector/styles.module.css
src/components/GitmojiList/Toolbar/styles.module.css

Add `outline` to `SearchInput` and `ListViewSelector` buttons

♿️ Improve toolbar a11y

---

package.json

🔧 Fix author package.json field

---

.github/CONTRIBUTING.md

Lot of developers ask why the tests are failing because of the snapshots. So I add some guideline for it in the `CONTRIBUTION` file

📝 Add steps for testing and snapshots update

---

.github/PULL_REQUEST_TEMPLATE.md

As we have had to remind our last 2 PR authors about this, I thought it was a good idea to add yet another reminder for opening an issue. :D 
funny thing how I didn't open an issue for this PR, in Brazil we have a meme for this occasion: "Finally, the hypocrisy", oh well :shrug:

📝 Add reminder to create an issue before opening a PR

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/Gitmoji/index.js
src/components/GitmojiList/__tests__/__snapshots__/gitmojiList.spec.js.snap

We don't need this className anymore as of #671

🎨 Remove gitmoji-${name} className

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

Hello @carloscuesta and @johannchopin ! 😎!
Emoji: ⚰️
Code: `:coffin:`
Description: Remove dead code
I would like to add coffin emoji because we can need to have an emoji to inform others about dead code deleted.
For example, we started a new project inside our monorepo but this project is cancelled. We need to delete it and a coffin fit perfectly to this usage.
Second example, you deleting old code not used anymore.
Thank you !
close #709

✨ Added remove dead code emoji (⚰️)

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/pages/related-tools.js

Fixes #736
Gitmoji-atom is an Atom package that helps you find the right gitmoji

:bento: Added link to gitmoji-atom

---

babel.config.json
package.json
src/pages/index.js
yarn.lock

⬆️ Bump Next.js to 11

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

:sparkles: Introduce "Improve developer experience" emoji

---

package.json
yarn.lock

Fixes https://github.com/carloscuesta/gitmoji/issues/931
As mentioned in the `next-pwa` changelog: https://github.com/shadowwalker/next-pwa/blob/master/CHANGELOG.md#542

⬆️ Bump `next-pwa` to fix PWA issues

---

src/utils/theme/theme.css

:wheelchair: (links) add option for prefer-reduced-motion

---

.github/ISSUE_TEMPLATE/gitmoji-proposal.md

:memo: Add more information on new emoji issue template

---

README.md
src/__tests__/__snapshots__/pages.spec.js.snap
src/pages/about.js

📝 Add example of usage

---

.github/workflows/npm-publish.yml

Hey! 👋🏼 
A small improvement to automate release changelogs

👷 Automate GitHub release publish

---

.github/workflows/ci.yml
.github/workflows/npm-publish.yml
package.json

⬆️ Bump `node` version to `16`

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/pages/related-tools.js

Add Alfred Gitmoji related tool

Add Alfred Gitmoji related tool

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

Add the 💸 emoji as described in #1063 
Fixes #1063

✨ Add 💸 emoji

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/pages/related-tools.js

Add [GitmojiApp](https://github.com/patrick-fu/GitmojiApp) in related tools page
```sh
➜  gitmoji git:(master) yarn test
......
Test Suites: 9 passed, 9 total
Tests:       33 passed, 33 total
Snapshots:   22 passed, 22 total
Time:        3.479 s
Ran all test suites.
✨  Done in 5.47s.
```

📝 Add GitmojiApp in related tools page

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

- Added the 🦺 emoji for use with commits containing code relating to validation.
Resolves #1136

✨ Add 🦺 emoji 

---

src/components/GitmojiList/Gitmoji/styles.module.css
src/components/GitmojiList/Toolbar/styles.module.css
src/utils/theme/theme.css

Hey! 👋🏼 
This fixes https://github.com/carloscuesta/gitmoji/issues/1173

🐛 Fix dark theme inconsistencies

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

✏️ Added some missing dots to the description

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/pages/related-tools.js

Updated related tools to include the Raycast extension

Add raycast to related tools page

---

.gitignore
packages/website/next.config.js
packages/website/package.json
turbo.json

Hey! 👋🏼 
Introduced this bug in #1235 as I forgot to update the `outputs` for the build command and `postbuild` script is not being triggered anymore as of yarn berry 🙈

🐛 Fix `build` static outputs

---

packages/gitmojis/package.json
packages/gitmojis/src/gitmojis.d.ts

Hey! 👋🏼 
Happy New Year everyone 🎉 , this PR adds type declarations to the `gitmojis` package 😊

🏷️ Add TypeScript type declarations to `gitmojis` package

---

packages/gitmojis/.lintstagedrc.json
packages/gitmojis/package.json
packages/gitmojis/src/schema.json
packages/website/src/components/GitmojiList/index.tsx
packages/website/src/pages/api/gitmojis/index.ts
yarn.lock

Hey! 👋🏼 
This PR replaces the `jsonlint` with `acv-cli` also updates the schema for validating the `gitmojis.json` file.

♻️ Replace `jsonlint` with `ajv-cli`

---

package.json
packages/website/src/pages/_app.tsx
yarn.lock

Hey! 👋🏼 
This PR enables vercel/analytics in website

✨ Enable `vercel/analytics` in website

---

packages/website/src/__tests__/__snapshots__/pages.spec.tsx.snap
packages/website/src/__tests__/pages.spec.tsx
packages/website/src/components/Layout/Hamburger/index.tsx
packages/website/src/pages/about.tsx
packages/website/src/pages/specification.tsx

Hey! 👋🏼 
Adding a specification page to explain a bit more in depth some concepts.
Fixes #1362

✨Add `specification` page

---

packages/website/src/__tests__/__snapshots__/pages.spec.tsx.snap
packages/website/src/components/CarbonAd/__tests__/__snapshots__/carbonAd.spec.tsx.snap
packages/website/src/components/CarbonAd/index.tsx

Hey!
I'm not able to reproduce the bug, but I believe this should fix #1396 
#1396

🐛 Render `CarbonAd` only when component is mounted

---

packages/website/src/pages/related-tools.tsx

The original gitmemoji repo is not active for a long period of time and the author cannot be contacted anymore. So, I decided to resurrect the repo and maintain it for the community of gitmoji.

✨ feat: update gitmemoji repo link

---

package.json
turbo.json
yarn.lock

Hey! 👋🏼 
This PR updates turborepo and runs `build` in dependencies.

🔧 Run turborepo `build` in dependencies

---

packages/gitmojis/src/gitmojis.json

Not sure if it's worth maintaining `entities` as part of the `gitmojis.json` but fixing the value for alembic on this PR.
Fixes https://github.com/carloscuesta/gitmoji/issues/1485

🐛 Fix `alembic` entity

---

packages/gitmojis/src/gitmojis.json
packages/website/src/components/GitmojiList/emojiColorsMap.ts

✏️ Update the `name` attribute of 💫

---

packages/website/src/components/Layout/Hamburger/index.tsx
packages/website/src/utils/theme/theme.css

This PR prevents scrolling when the hamburger menu is open.
Closes #1629

🚸 Prevent scrolling when hamburger menu is open

---

packages/website/src/pages/related-tools.tsx

i developed an flow launcher plugin to search for gitmojis fast on windows. it's pretty much the same as powertoys run but with custom plugins and more functionality ^-^ i would love to see the plugin featured under related tools on https://gitmoji.dev/related-tools 😜
my repo: https://github.com/tho-myr/Flow.Launcher.Plugin.Gitmoji_Plus
#1866 ✨ add flow launcher gitmoji plugin to tools

✨ add flow launcher gitmoji plugin to tools
