src/styles/style.scss

For some emoijs fonts provide own black glyhps (like ⬆️ or 🌐). By explict setting the font-family to the different emoijs fonts we get the colorful versions.

🐛 Use explict emoij fonts

---

gulpfile.babel.js

The default gulp task – `dev`, which is just `templates`, `styles`, and `serve` – doesn't work the first time you run it. Since files in the templates reference built styles, `templates` needs to depend on `styles`. Since `serve` serves built files, it needs to wait on both `templates` and `styles` to finish before doing its thing.
Tangent: I used the gitmoji for "config files" but I'm not sure that's
apt. Do we need a gitmoji for "dev/internal improvements"?

🔧 templates depend on styles; serve depends on both being done

---

src/styles/style.scss

Instead of animating `box-shadow` on an element, it is recommended to use a pseudo element and animate it's `opacity`. Properties besides `opacity` and `transform` will trigger some repaint which is more GPU intensive, especially on mobile

⚡️ improve performance of card hover effect

---

src/data/gitmojis.json

Motivation: IMHO "Removing a dependency" should be in the same line as "Adding a dependency" and also after it.

:lipstick: Change "Removing a dependency" position

---

README.md

Dodgy sentence made me scratch my head for a moment.
Simply replace an erroneous _it's_ --> _is_

:pencil2: Fix typo in the README

---

src/data/gitmojis.json
src/styles/_includes/_vars.scss

This PR addresses https://github.com/carloscuesta/gitmoji/issues/183
(was originally https://github.com/carloscuesta/gitmoji/issues/330) 
I think an emoji for changes related to feature flags would be swell.
In my day job, I am using 🏁 , though I see you have designated that one for windows changes (🤷‍♂ c'est la vie).
I propose:
Emoji: 🚩
Code: `:triangular_flag_on_post:`
Description: Adding, updating, or removing feature flags
Entity: `&#x1F6A9;`

✨ Add 🚩 for changes to feature flags

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/Gitmoji/index.js
src/components/GitmojiList/__tests__/__snapshots__/gitmojiList.spec.js.snap
src/components/GitmojiList/index.js
src/styles/_includes/_notifications.scss
src/styles/style.scss

Implementation of issue #419 
- User is able to click on the emoji to get the emoji copied in clipboard and he also can click on the gitmoji 'code' that produce the current behaviour (copy gitmoji)
- Gitmoji 'code' is wrapped in a clickable area wich has the same bg-color as the `emoji-header`
- Gitmoji 'emoji' is animated on hover to enforce UX (catchy animation to say that this area is clickable too)
- The alert message specifying what you have copied. It can be both:
- `Hey! Gitmoji emoji 🎨 copied to the clipboard 😜`
- `Hey! Gitmoji :art: copied to the clipboard 😜`
[![Feature demo][1]][1]
[1]: https://i.stack.imgur.com/Jtorg.gif

✨ Copy Gitmoji if click on the code and copy emoji if click on it

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

This will enable :tada: to be used more than once in a repository since
we can have multiple projects in a monorepo, for example. Or it can be
used in a library repository, to add a playground project to test
this library.
Closes #294

Reword :tada: to "Begining a project"

---

.travis.yml
package.json

Instead of using `github-pages` for hosting the site. We're moving it to vercel,
to have Deploy Previews for the PRs.
This fixes #481
Once this is merged I should update the DNS of `gitmoji.carloscuesta.me` to point to vercel

🔧 Move site to Vercel

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

Previously only for files, now for files, any path and any route.
Closes #243

✨ generalize truck emoji to fit in more cases

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/data/gitmojis.json

I made the description of the documentation gitmoji for :memo: conform to the pattern established in many of the other gitmojis. Also, instead of using the nickname "docs" I expanded this into "documentation." I think it is more consistent with the rest of the codebase considering we use "dependencies" instead of "deps."

Revise pencil gitmoji

---

src/components/GitmojiList/Gitmoji/styles.module.css
src/components/Layout/Header/styles.module.css
src/utils/theme/theme.css

As I said on #622 one of the reasons behind this refactor was to implement dark-mode, so in this PR i'm revamping #423 by @benavern and implementing a first version of the theme :tada:
From this point we can iterate over the dark version of the website 😊 
cc @vhoyer @johannchopin 
This fixed #423
Thanks to @benavern for the work and the patience 👏🏼  ❤️

💄 Add dark-mode theme

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/Toolbar/index.js
src/components/GitmojiList/__tests__/__snapshots__/gitmojiList.spec.js.snap
src/components/GitmojiList/__tests__/gitmojiList.spec.js
src/components/GitmojiList/index.js

This should allow the users to find emojis by description as well, for a better UX.
Closes: #640

✨ Allow searching by gitmoji description

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/gitmoji-proposal.md

Add different `ISSUE_TEMPLATES` rather than having just a single one. This will make users pick one of both templates before creating an issue. Those issues will be labeled automatically

📝 Add issue templates

---

.github/CONTRIBUTING.md
src/data/gitmojis.json
src/data/schema.json

Closes: #429
This PR adds a `semver` property to each Gitmoji. The `semver` property can be `'major'` for breaking changes, `'minor'` for new features, `'patch'` for bugfixes/small improvements and `null` if the commit doesn't affect the version of the package.
Gitmojis are too granular, and we need a higher level grouping to know what kind of effect does each gitmoji/commit have on the project, which is necessary to be able to automate the package publishing process and so on.
Right now, there are some third-party projects that try to do this grouping on their side, but because there is a big room of interpretation of each emoji, they are not consistent.
- This is my interpretation of the gitmojis, please drop your comments, so we find a common ground.
- The semantic versioning effect is …

✨ Add `semver` property to the gitmojis

---

src/__tests__/pages.spec.js
src/__tests__/stubs.js
src/pages/api/gitmojis/index.js

Hello! 👋🏼 
This PRs introduces the first endpoint of the `Gitmoji` API 🎉 
The main idea behind this endpoint would be to fix the following error that some users of `gitmoji-cli` that live on countries that block `raw.githubusercontent.com` get - https://github.com/carloscuesta/gitmoji-cli/issues/552
The gitmojis could be consumed through the following endpoint: 
```
GET: https://gitmoji.dev/api/gitmojis
```
To implement this as an API endpoint we're using the [Next.js API Routes feature](https://nextjs.org/docs/api-routes/introduction)

✨ Introduce Gitmoji API

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/__tests__/__snapshots__/gitmojiList.spec.js.snap
src/data/gitmojis.json

Some emojis are rendered as text by default, other as image. The result
is that some gitmojis are different / a bit ugly depending on the font
used. This concerns only the unicode version of the gitmoji, not the
:code: one.
Emojis are rendered either by text or picture. Variation selectors
VS15 and VS16 define if text or picture representation should be used.
According to [0], the following gitmojis are affected by those selectors
and may be rendered as text:
- alembic
- alien
- ambulance
- *arrow-down
- *arrow-up
- building-construction
- card-file-box
- *coffin
- *label
- lock
- mag
- package
- *pencil2
- *recycle
- rewind
- wastebasket
- *wheelchair
- *zap
Out of those, 8 already have VS16 (\ufe0f), and will be rendered as
image. This commit unifies the 10 other ones by adding the …

:bug: Render unicode gitmojis as image by default

---

.github/workflows/npm-publish.yml
package.json

Hello! 👋🏼 
This PR automates the process of publishing the package to the `npm` registry. Every time that a new tag `v*` is pushed to the repository, automatically the `npm-publish.yml` github workflow will start to publish the package to the registry.

🔧 Automate npm publish with a GitHub Action

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

These changes are intended for the Test Driven Development cycle. The proposal is the following:
1. 🧪 Add a failing test
1. ✅ Make the test pass
1. ♻️ Refactor the code
This PR updates the description of ✅ to _"Make the tests pass"_ and adds 🧪 for "_Add or update tests_."
Discussion at #284

Add 🧪 emoji for TDD. Fixes (#284)

---

package.json
src/__tests__/__snapshots__/pages.spec.js.snap
src/__tests__/pages.spec.js
src/__tests__/stubs.js
src/components/ContributorsList/Contributor/index.js
src/components/ContributorsList/__tests__/__snapshots__/contributorsList.spec.js.snap
src/components/ContributorsList/__tests__/contributorsList.spec.js
src/components/ContributorsList/__tests__/stubs.js
src/components/ContributorsList/index.js
src/pages/contributors.js
yarn.lock

This fixes https://github.com/carloscuesta/gitmoji/issues/827

✨ Fetch Contributors using `getStaticProps`

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

We have ✨ for additional features, but "features" for some projects imply only public behaviors. Adding utility functions, interfaces, wrappers, or any business/domain logic, for most public-facing libraries/projects would not be considered a "new feature". These additions live in the business/domain layer and are only for internal usage and will never be exposed via UI or API. Therefore, there is no good emoji in gitmoji to represent clearly that the addition or change is only meant for the business/domain layer.
👔 as suggested by #723 would resolve all these internal business logic commits and clarify that additions/changes are internal, not public, and live in the business/domain layer.
This may have some overlap with ♻️ (representing refactoring) as a change to business logic could …

Add emoji business logic Resolves #723

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

Introduces the 🩺 `:stethoscope:` emoji for healthchecks. Discuss the need for this emoji in #668 .

Add Stethoscope 🩺 for Healthchecks (fixes #668)

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

As described and researched in Issue #883, this PR adds the `:brick:` emoji to describe "infrastructure related changes"
- [x ] All tests passed.

✨ Add brick 🧱 to Gitmoji

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/pages/related-tools.js

Due to the transfer of the project from [vtrois/gitmoji-vscode](https://github.com/vtrois/gitmoji-vscode) to [seatonjiang/gitmoji-vscode](https://github.com/seatonjiang/gitmoji-vscode) need to change the url.

🍱 Modify project url and description

---

.github/ISSUE_TEMPLATE/gitmoji-proposal.md

Since it appear that people weren't too keen on answering the questions when it was in comment format, also this should save some time for maintainers and issue authors alike since we will hopefully skip the initial interactions.

:memo: Add a more in your face questions on issue template

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

Relates to https://github.com/carloscuesta/gitmoji/issues/922
Adds an Emoji for adding/removing secrets.
Whether or not its _good_ practice, many programmers version secrets in git repositories with `git-crypt`, `SOPS`, etc.

:sparkles: Add 'Add or Remove Secrets.' :closed_lock_with_key: emoji

---

src/pages/related-tools.js

Add Gitmoji::Regex for Ruby to `src/pages/related-tools.js`
See #1011 
https://github.com/pboling/gitmoji-regex
The Ruby Gitmoji Regex will be useful for testing strings for the presence of Gitmoji characters.  It relies on the [gitmoji JSON](https://github.com/carloscuesta/gitmoji/blob/master/src/data/gitmojis.json) from this project, and has a script for updating, as well as a spec that will fail the build as soon as it gets out of sync with this canon.

Add gitmoji-regex

---

package.json
yarn.lock

The end user doesn't need to install this dependencies. These are only used for the website.
Fixes: #1102
I moved the dependencies to dev dependencies.
I only updated the package.json. The yarn.lock also needs updating.

Move dependencies to dev dependencies

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/components/GitmojiList/emojiColorsMap.js
src/data/gitmojis.json

Add the 🧵 emoji as described in https://github.com/carloscuesta/gitmoji/issues/1031
Fixes https://github.com/carloscuesta/gitmoji/issues/1031

✨ Add 🧵 emoji

---

src/data/gitmojis.json

The hex number used for the recycle emoji is 0x267b and the entity is 0x2672.
The code name suggest 0x267b.
Also [emojipedia on 0x2672](https://emojipedia.org/universal-recycling-symbol/):
This Unicode character has no emoji version, meaning this is intended to
display only as a black and white glyph on most platforms. It has not been
Recommended For General Interchange (RGI) — as an emoji — by Unicode.
Change entity to 0x267b.

:adhesive_bandage: use for recycle emoji and entity same number

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/pages/related-tools.js

Fixes https://github.com/carloscuesta/gitmoji/issues/1109
Adds https://github.com/ma1ted/githubmoji to `/related-tools`

✨ Add githubmoji to /related-tools

---

src/__tests__/__snapshots__/pages.spec.js.snap
src/pages/related-tools.js

This PR adds a reference to  [sercanuste/gitmoji-changelog-action](https://github.com/sercanuste/gitmoji-changelog-action) repository at Related Tools page.
I developed a GitHub Action for auto generate CHANGELOG with [gitmoji-changelog](https://github.com/frinyvonnick/gitmoji-changelog).
You can access to the action on [GitHub Marketplace](https://github.com/marketplace/actions/generate-gitmoji-changelog).

✨ Add gitmoji-changelog-action to related tools

---

src/components/GitmojiList/__tests__/gitmojiList.spec.js
src/components/GitmojiList/index.js

Fixes Issue: #1163 
Compare searchinput with emojis in the data. Showing the emoji that match.
Examples:

✨Add support to search by emoji

---

.github/dependabot.yml

Hey! 👋🏼 
This PR enables Dependabot for GitHub-actions dependencies.

🔧 Enable `dependabot` for `github-actions`

---

packages/gitmojis/package.json
turbo.json

Hey! 👋🏼 
This PR runs the `lint` script before publishing the package to the registry using turborepo.

👷 Run `lint` before `publishPackage` with turbo

---

packages/website/src/components/GitmojiList/Toolbar/ListModeSelector/styles.module.css
packages/website/src/components/GitmojiList/Toolbar/ThemeSelector/styles.module.css
packages/website/src/utils/theme/theme.css

The dark mode and the light mode are not coherent. When you change the mode you can see that the buttons on the right of the search are in one case in over-brightness and in the other not.
I added the CSS attributes to be coherent. I took the opportunity to remove one that was duplicated.
Close #1231

:lipstick: Update UI Toolbar Button

---

packages/website/package.json
yarn.lock

I have follow doc from https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
Currently, the plugin sort like this: 
```js
// 1. node "builtin" &  "external" modules
import fs from 'fs';
import path from 'path';
import _ from 'lodash';
import chalk from 'chalk';
// # a space between
// 2. "internal" & "parent" & "sibling" & "index" modules
import foo from 'src/foo';
import foo from '../foo';
import qux from '../../foo/qux';
import bar from './bar';
import baz from './bar/baz';
import main from './';
```
If necessary, I can edit and sort the imports alphabetically.
Close #1243

🔧 Add `eslint-plugin-import` plugin

---

packages/website/src/__tests__/__snapshots__/pages.spec.tsx.snap
packages/website/src/components/GitmojiList/Toolbar/index.tsx
packages/website/src/components/GitmojiList/__tests__/__snapshots__/gitmojiList.spec.tsx.snap

Hey! 👋🏼 
This PR updates the search input type to `search` to show the clear button and enable `ESC` key as a clear key.
Fixes https://github.com/carloscuesta/gitmoji/issues/1190

🚸 Update search input `type`

---

packages/website/src/__tests__/__snapshots__/pages.spec.tsx.snap
packages/website/src/components/GitmojiList/Gitmoji/index.tsx
packages/website/src/components/GitmojiList/Gitmoji/styles.module.css
packages/website/src/components/GitmojiList/__tests__/__snapshots__/gitmojiList.spec.tsx.snap

:children_crossing: Better wrap lines for gitmoji codes for better readability

---

packages/website/src/pages/related-tools.tsx

- Added [Genmoji](https://genmoji.xyz) mention in the related tools section
Genmoji generates a suitable commit message associated with a fitting gitmoji using the openAI API, so would be interesting to have it mentioned on the gitmoji website itself.
- https://github.com/carloscuesta/gitmoji/issues/1387

📝 Related Tools: add Genmoji

---

packages/website/src/pages/related-tools.tsx

A PR to add a  link to the [`gitmoji-fuzzy-hook`](https://gitlab.com/raabf/gitmoji-fuzzy-hook) to the related tools page.
It is a tool which can be installed as git-commit-hook. Every time you make an `git commit` (either with or without `-m` or  from a GUI) you can select an emoji and it will be prepended to the git commit message so that you do never forget to select a gitmoji and do not have to copy a gitmoji via clipboard.
I use it sucessfully for some years now. I would be glad if you can add it :smile: .
No one

📝(related tools): Add gitmoji-fuzzy-hook

---

.github/CONTRIBUTING.md
packages/website/src/__tests__/__snapshots__/pages.spec.tsx.snap
packages/website/src/components/GitmojiList/Toolbar/Kbd/index.tsx
packages/website/src/components/GitmojiList/Toolbar/Kbd/styles.module.css
packages/website/src/components/GitmojiList/Toolbar/index.tsx
packages/website/src/components/GitmojiList/Toolbar/styles.module.css
packages/website/src/components/GitmojiList/__tests__/__snapshots__/gitmojiList.spec.tsx.snap

Fixes #1396 (or at least a part of it)
The issue there was that for non-macos users the client-side rendered content differed from server-side rendered content.
We now use a `useEffect` so React does not complain anymore about this.
I also updated `isMacOs` to return `false` by default.

:bug: Text content does not match server-rendered HTML

---

packages/website/src/__tests__/__snapshots__/pages.spec.tsx.snap
packages/website/src/components/Icon/__tests__/__snapshots__/icon.spec.tsx.snap
packages/website/src/components/Icon/definitions.tsx
packages/website/src/components/Layout/Header/index.tsx
packages/website/src/components/Layout/__tests__/__snapshots__/layout.spec.tsx.snap

After the rebranding of twitter to X by Elon Musk, it might be pertinent to update the "tweet" button. It does look a bit off and twitter still has more brand recognition than X, but I leave that up to the maintainers of gitmoji to pick what they prefer.  
https://github.com/carloscuesta/gitmoji/issues/1563

change twitter to twitter-x icon

---

.github/ISSUE_TEMPLATE/gitmoji-proposal.yml
packages/gitmojis/src/gitmojis.json
packages/website/src/__tests__/__snapshots__/pages.spec.tsx.snap

Extends 🔒 `:lock:` gitmoji to include security and privacy.
Closes #1445
---
Extends 🔒 `:lock:` gitmoji to include security and privacy.
#1445

✨ Extend lock gitmoji to include privacy

---

package.json
packages/website/package.json
pnpm-lock.yaml

👋 hey! I'm coming from https://www.shew.dev/monorepos/examples, just moved `@vercel/analytics` to the `packages/website` from the monorepo root. 😁👍

♻️ Move `@vercel/analytics` to website as a dependency

---

packages/gitmojis/src/gitmojis.json
packages/website/src/__tests__/__snapshots__/pages.spec.tsx.snap
packages/website/src/components/GitmojiList/emojiColorsMap.ts

As discussed [here](https://github.com/carloscuesta/gitmoji/issues/1868), this PR adds the ✈️ emoji to signify changes related to offline support!
Also updates the snapshots for tests to pass ✅ 
https://github.com/carloscuesta/gitmoji/issues/1868

✨ Adds ✈️ for offline support
